version: '3'

services:
  webserver:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./etc/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./var/www/certbot/:/var/www/certbot/:ro
      - ./etc/letsencrypt/:/etc/letsencrypt/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./var/www/certbot/:/var/www/certbot/:rw
      - ./etc/letsencrypt/:/etc/letsencrypt/:rw